// Auto-derived from site.config.ts — do not edit this file directly.
// Edit src/config/site.config.ts instead.
import { ORG_NAME } from './site.config';

export const APP_DEFAULTS = {
  orgName: ORG_NAME,
  logoUrl: '',
  darkMode: false,
};
