// Auto-derived from site.config.ts — do not edit this file directly.
// Edit src/config/site.config.ts instead.
import { COVER, KPIS, INFO_CARDS } from '@/config/site.config';

export interface CoverKPI {
  id: string;
  label: string;
  value: string;
  icon: string;
}

export interface CoverInfoCard {
  id: string;
  title: string;
  icon: string;
  items: string[];
}

export interface CoverQuickLink {
  id: string;
  label: string;
  route: string;
}

export interface CoverConfig {
  headline: string;
  headlineHighlight: string;
  subtitle: string;
  trustPills: { icon: string; label: string }[];
  kpis: CoverKPI[];
  infoCards: CoverInfoCard[];
  quickLinks: CoverQuickLink[];
  portalPreviewTitle: string;
}

export const DEFAULT_COVER_CONFIG: CoverConfig = {
  headline: COVER.headline,
  headlineHighlight: COVER.headlineHighlight,
  subtitle: COVER.subtitle,
  trustPills: COVER.trustPills,
  portalPreviewTitle: COVER.portalPreviewTitle,
  quickLinks: COVER.quickLinks,
  kpis: KPIS,
  infoCards: INFO_CARDS,
};
