// Auto-derived from site.config.ts — do not edit this file directly.
// Edit src/config/site.config.ts instead.
import { DASHBOARDS } from '@/config/site.config';

export interface Dashboard {
  id: string;
  title: string;
  description: string;
  category: string;
  tags: string[];
  status: 'Live Data' | 'Preview';
  featured: boolean;
  iconName: string;
  embedUrl: string;
}

export const CATEGORIES = [
  'Executive',
  'Budget',
  'Fees/Receivables',
  'Cash',
  'Payroll',
  'Procurement',
  'AP',
  'Capex',
  'Compliance',
  'Close Pack',
  'Reconciliation',
  'P&L',
  'Students',
  'Trial Balance',
  'Vendors',
] as const;

export const CATEGORY_ICON_FALLBACKS: Record<string, string> = {
  Executive: 'Crown',
  Budget: 'PiggyBank',
  'Fees/Receivables': 'Receipt',
  Cash: 'Banknote',
  Payroll: 'Users',
  Procurement: 'ShoppingCart',
  AP: 'FileText',
  Capex: 'Building',
  Compliance: 'ShieldCheck',
  'Close Pack': 'PackageCheck',
  Reconciliation: 'ArrowLeftRight',
  'P&L': 'TrendingUp',
  Students: 'GraduationCap',
  'Trial Balance': 'BookOpen',
  Vendors: 'Truck',
};

export const DEFAULT_DASHBOARDS: Dashboard[] = DASHBOARDS;
